routes/web.php
<?php

declare(strict_types=1);

use Bittacora\Bpanel4\Vat\Http\Controllers\VatRateRegionsAdminController;
use Bittacora\Bpanel4\Vat\Http\Controllers\VatRatesAdminController;

Route::prefix('bpanel/tipos-iva')->name('bpanel4-vat-rates.bpanel.')
    ->middleware(['web', 'auth', 'admin-menu'])->group(function () {
        Route::get('/', [VatRatesAdminController::class, 'index'])->name('index');
        Route::get('/nuevo', [VatRatesAdminController::class, 'create'])->name('create');
        Route::post('/guardar', [VatRatesAdminController::class, 'store'])->name('store');
        Route::get('{vatRate}/editar', [VatRatesAdminController::class, 'edit'])->name('edit');
        Route::post('{vatRate}/actualizar', [VatRatesAdminController::class, 'update'])->name('update');
        Route::delete('{vatRate}/eliminar', [VatRatesAdminController::class, 'destroy'])->name('destroy');
        Route::get('{vatRate}/establecer-como-iva-envio', [VatRatesAdminController::class, 'setShippingVatRate'])->name('setShippingVatRate');
    });


Route::prefix('bpanel/regiones-tipos-iva')->name('bpanel4-vat-rates.bpanel.regions.')
    ->middleware(['web', 'auth', 'admin-menu'])->group(function () {
        Route::get('{vatRate}/anadir-region', [VatRateRegionsAdminController::class, 'create'])->name('create');
        Route::post('/anadir-region', [VatRateRegionsAdminController::class, 'store'])->name('store');
        Route::get('/{vatRateRegion}/editar-region', [VatRateRegionsAdminController::class, 'edit'])->name('edit');
        Route::post('/{vatRateRegion}/editar-region', [VatRateRegionsAdminController::class, 'update'])->name('update');
        Route::delete('/{vatRateRegion}/eliminar-region', [VatRateRegionsAdminController::class, 'destroy'])->name('destroy');
    });

resources/views/bpanel/_form.blade.php
<form class="mt-lg-3" autocomplete="off" method="post" action="{{ $action }}" enctype="multipart/form-data">
    @csrf
    @livewire('form::input-text', [
        'name' => 'name',
        'labelText' => __('bpanel4-vat-rates::vat-rate.name'),
        'required'=>true,
        'value' => old('name') ?? $vatRate?->getName()
    ])
    @livewire('form::input-number', [
        'name' => 'rate',
        'labelText' => __('bpanel4-vat-rates::vat-rate.rate'),
        'required'=>true,
        'value' => old('rate') ?? $vatRate?->getRate(),
        'min' => 0, 'step' => 0.01,
        'fieldWidth' => 7,
        'labelWidth' => 3
    ])
    @livewire('form::input-checkbox', [
        'name' => 'active',
        'value' => 1,
        'labelText' => __('bpanel4-vat-rates::vat-rate.active'),
        'bpanelForm' => true,
        'checked' => $vatRate?->isActive()
    ])
    @if($vatRate !== null)
        <div class="px-4">
            <strong class="pb-3">Regiones:</strong>
            <div style="color: #777; font-size: .9rem;font-style: italic;">En este apartado puede cambiar el valor de este impuesto para distintas regiones. Por ejemplo, para el IVA general
            puede hacer que el tipo aplicado para las Islas Canarias, Ceuta y Melilla sea 0.</div>
        </div>
        <div class="px-4 pt-4">
            <a class="btn btn-primary mt-3" href="{{ route('bpanel4-vat-rates.bpanel.regions.create', ['vatRate' => $vatRate]) }}">
                <i class="fas fa-plus"></i> Añadir IVA personalizado para una región
            </a>
        </div>
    @endif
    <div class="col-12 mt-5 border-t-1 bgc-secondary-l4 brc-secondary-l2 py-35 d-flex justify-content-center">
        @livewire('form::save-button',['theme'=>'update'])
        @livewire('form::save-button',['theme'=>'reset'])
    </div>
</form>

resources/views/bpanel/create.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', __('bpanel4-vat::form.new-vat-rate'))

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('bpanel4-vat::form.new-vat-rate') }}</span>
            </h4>
        </div>
        @include('bpanel4-vat-rates::bpanel._form', ['panelTitle' => __('bpanel4-vat::form.new-vat-rate')])
    </div>
@endsection

resources/views/bpanel/edit.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', __('bpanel4-vat::form.edit-vat-rate'))

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('bpanel4-vat::form.edit-vat-rate') }}</span>
            </h4>
        </div>
        @include('bpanel4-vat-rates::bpanel._form', ['panelTitle' => __('bpanel4-vat::form.edit-vat-rate')])
    </div>

    <div class="card bcard mt-5">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('bpanel4-vat::form.regions') }}</span>
            </h4>
        </div>
        <div class="p-4">
            @livewire('bpanel4-vat-rates::livewire.vat-rate-region-datatable', ['vatRateId' => $vatRate->getId()])
        </div>
    </div>
@endsection

resources/views/bpanel/index.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', 'Tipos de IVA')

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('bpanel4-vat::datatable.index') }}</span>
            </h4>
        </div>
        <div class="card-body">
            @livewire('bpanel4-vat-rates::livewire.vat-rate-datatable', [], key('bpanel4-vat-datatable'))
        </div>
    </div>
@endsection

resources/views/bpanel/livewire/vat-rate-datatable.blade.php
<td class="align-middle">
    <div class="text-center">
        {{ $row->name }}
    </div>
</td>
<td class="align-middle">
    <div class="text-center">
        {{ $row->rate }} %
    </div>
</td>
<td class="align-middle">
    <div class="text-center">
        @if($row->apply_to_shipping)
            <a class="btn btn-success btn-xxs mb-1" title="Activado">
                <i class="fa fa-check"></i>
            </a>
        @else
            <a class="btn btn-danger btn-xxs mb-1" title="Desactivado" href="{{ route('bpanel4-vat-rates.bpanel.setShippingVatRate', ['vatRate' => $row]) }}">
                <i class="fa fa-times"></i>
            </a>
        @endif
    </div>
</td>
<td class="align-middle">
    <div class="text-center">
        @livewire('utils::datatable-default', [
            'fieldName' => 'active',
            'model' => $row,
            'value' => $row->active,
            'size' => 'xxs'
        ], key('active-user-'.$row->id))
    </div>
</td>
<td class="align-middle">
    <div class="text-center">
        @livewire('utils::datatable-action-buttons', [
            'actions' => ["edit", "delete"],
            'scope' => 'bpanel4-vat-rates.bpanel',
            'model' => $row,
            'permission' => ['edit', 'delete'],
            'id' => $row->id,
            'message' => 'el tipo de iva?'
        ], key('user-buttons-'.$row->id))
    </div>
</td>

resources/views/livewire/vat-rate-datatable.blade.php
<td class="align-middle">
    <div class="text-center">
        {{$row->name}}
    </div>
</td>
<td class="align-middle">
    <div class="text-center">
        {{$row->reference}}
    </div>
</td>
<td class="align-middle">
    <div class="text-center">
        {{$row->size}} {{$row->unit}}
    </div>
</td>
<td class="text-center align-middle">
    @if (count($row->sizes))
        <span class="badge badge-primary">{{ count($row->sizes) }}</span></h1>
    @endif
</td>
<td class="align-middle">
    <div class="text-center">
        {{ $row->price }} €
    </div>
</td>
<td class="align-middle">
    @if(!empty($row->discounted_price))
        <div class="text-center">
            {{ $row->discounted_price }} €
        </div>
    @endif
</td>
<td class="align-middle">
    <div class="text-center">
        {{\Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $row->created_at)->format('d/m/Y')}}
    </div>
</td>
<td class="align-middle">
    @livewire('utils::datatable-default', ['fieldName' => 'active', 'model' => $row, 'value' => $row->active, 'size' => 'xxs'], key('active-user-'.$row->id))
</td>
<td class="align-middle">
    <div class="text-center">
        @livewire('utils::datatable-action-buttons', ['actions' => ["edit", "delete"], 'scope' => 'bpanel4-vat-rates', 'model' => $row, 'permission' => ['edit', 'delete'], 'id' => $row->id, 'message' => 'el producto?'], key('user-buttons-'.$row->id))
    </div>
</td>